version: '3'

networks:
  laravel:

services:
  app:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./backend:/var/www/html:delegated
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on: 
      - php
    networks:
      - laravel

  php:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    volumes:
      - ./backend:/var/www/html:delegated
    networks:
      - laravel

  composer:
    build:
      context: ./backend
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    volumes:
      - ./backend:/var/www/html
    depends_on:
      - php
    entrypoint: [ 'composer', '--ignore-platform-reqs' ]
    networks:
      - laravel

  artisan:
    build:
      context: ./backend
    volumes:
      - ./backend:/var/www/html:delegated
    entrypoint: [ 'php', '/var/www/html/artisan' ]
    networks:
      - laravel
